from typing import Any, Type

class RaisesContext:
    def __enter__(self) -> "RaisesContext": ...
    def __exit__(self, exc_type: Type[BaseException] | None, exc: BaseException | None, tb: Any) -> bool: ...

def raises(expected_exception: type[BaseException], *args: Any, **kwargs: Any) -> RaisesContext: ...
